### ISSUE TITLE
ImportError: Failed to import _strptime because the import lockis held by another thread.

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#2198]
Platform: 
Version: 3.0.7

ImportError Import can't find module, or can't find name in module.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 54, in run
    yield self.operation()

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/certificate_check.py", line 75, in operation
    yield self.check_tenants_for_cert_expiration()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 101, in _wrap
    result = function(self.instance, session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/certificate_check.py", line 43, in check_tenants_for_cert_expiration
    self.cert_expiration_checks(session, tenant[0])

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/certificate_check.py", line 52, in cert_expiration_checks
    expiration_date = letsencrypt.convert_asn1_date(cert.get_notAfter())

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/letsencrypt.py", line 21, in convert_asn1_date
    return datetime.strptime(asn1_bytes,'%Y%m%d%H%M%SZ')

ImportError: Failed to import _strptime because the import lockis held by another thread.

**Comment by evilaliv3** [comment]
Closing as outdated.
