### ISSUE TITLE
KeyError Mapping key not found on GlobaLeaks 3 from field

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#2201]
Platform: 
Version: 3.0.7

KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 103, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 227, in update_field
    field = db_update_field(session, tid, field_id, field, language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 192, in db_update_field
    db_update_fieldattrs(session, tid, field.id, field_dict['attrs'], language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 91, in db_update_fieldattrs
    attrs_ids = [db_update_fieldattr(session, tid, field_id, attr_name, attr, language) for attr_name, attr in field_attrs.items()]

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 76, in db_update_fieldattr
    if attr_dict['type'] == 'bool':

KeyError: 'type'

**Comment by secomi** [comment]
Hello, 

if it helps, I have the same problem with the version 3.1.9.
When 
 1. I create a question of type: Multi-line text input
 2. input validation set to something different than BLANK (eg: none, email address),
 3. then each time I save I get the exception error.

**Comment by evilaliv3** [comment]
Closing as outdated.
