### ISSUE TITLE
TypeError: Cannot read property 'user_id' of undefined on /login

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#2204]
Platform: 
Version: 3.0.5

URL: /login

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

Error Message: TypeError: Cannot read property 'user_id' of undefined

Stacktrace:
[
  {
    "source": "    at m.$scope.showDeleteWBFile (https://xxxx/js/scripts.js:18489:35)", 
    "columnNumber": 35, 
    "fileName": "https://xxxxxx/js/scripts.js", 
    "functionName": "m.$scope.showDeleteWBFile", 
    "lineNumber": 18489
  }, 
  {
    "source": "    at fn (https://xxxxxxx/js/scripts.js:253:306", 
    "columnNumber": 306, 
    "fileName": "https://xxxxxxx/js/scripts.js", 
    "functionName": "fn", 
    "lineNumber": 253
  }, 
  {
    "source": "    at m.$digest (https://xxxxxx/js/scripts.js:159:310)", 
    "columnNumber": 310, 
    "fileName": "https://xxxxxx/js/scripts.js", 
    "functionName": "m.$digest", 
    "lineNumber": 159
  }, 
  {
    "source": "    at m.$apply (https://xxxxxx/js/scripts.js:162:355)", 
    "columnNumber": 355, 
    "fileName": "https://xxxxxxx/js/scripts.js", 
    "functionName": "m.$apply", 
    "lineNumber": 162
  }, 
  {
    "source": "    at l (https://xxxxxx/js/scripts.js:114:167)", 
    "columnNumber": 167, 
    "fileName": "https://xxxxxx/js/scripts.js", 
    "functionName": "l", 
    "lineNumber": 114
  }, 
  {
    "source": "    at t (https://xxxxxx/js/scripts.js:119:228)", 
    "columnNumber": 228, 
    "fileName": "https://xxxxx/js/scripts.js", 
    "functionName": "t", 
    "lineNumber": 119
  }, 
  {
    "source": "    at XMLHttpRequest.A.onload (https://xxxxxxx/js/scripts.js:120:139)", 
    "columnNumber": 139, 
    "fileName": "https://xxxxxxx/js/scripts.js", 
    "functionName": "XMLHttpRequest.A.onload", 
    "lineNumber": 120
  }
]

**Comment by evilaliv3** [comment]
Closing as outdated.
