### ISSUE TITLE
socks unhandled exception: TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#2297]
Platform: 
Host:  ()
Version: 3.0.29

TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()

  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)

  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)

  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in dataReceived
    return self._wrappedProtocol.dataReceived(data)

  File "/home/travis/build/globaleaks/GlobaLeaks/backend/globaleaks/utils/socks.py", line 112, in dataReceived
    getattr(self, 'socks_state_%s' % self.state)()

  File "/home/travis/build/globaleaks/GlobaLeaks/backend/globaleaks/utils/socks.py", line 70, in socks_state_2
    self.error(Failure(SOCKSError(ord(self._buf[1]))))

TypeError: ord() expected string of length 1, but int found

**Comment by evilaliv3** [comment]
Closing as outdated.
