### ISSUE TITLE
unhandled exception in /submission on TypeError: field.attrs.min_len is undefined

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#2310]
Platform: Host:  ()
Version: 3.0.29

URL: /submission

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

Error Message: TypeError: field.attrs.min_len is undefined

Stacktrace:
[
  {
    "source": "$~~~~~~@~~~~~~://xxxxxx/js/scripts.js:20832:7", 
    "columnNumber": 7, 
    "fileName": "http://xxxxx/js/scripts.js", 
    "functionName": "$scope.onAnswerUpdate", 
    "lineNumber": 20832
  },

**Comment by fpietrosanti** [comment]
Happening also on 3.1.9 on UniPD site TEST URL http://147.162.80.14


Platform: 
Host:  
Version: 3.1.9

URL: /submission

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

Error Message: TypeError: field.attrs.min_len is undefined

Stacktrace:
[
  {
    "source": "$~~~~~~@~~~~~~://SITO/js/scripts.js:20328:7",
    "columnNumber": 7,
    "fileName": "http://SITO/js/scripts.js",
    "functionName": "$scope.onAnswerUpdate",
    "lineNumber": 20328
  },
  {
    "source": "~~~~~~@~~~~~~://SITO/js/scripts.js line 255 > Function:4:299",
    "columnNumber": 299,
    "fileName": "http://SITO/js/scripts.js line 255 > Function",
    "functionName": "fn",
    "lineNumber": 4
  },
  {
    "source": "$~~~~~~@~~~~~~://SITO/js/scripts.js:162:510",
    "columnNumber": 510,
    "fileName": "http://SITO/js/scripts.js",
    "functionName": "$eval",
    "lineNumber": 162
  },
  {
    "source": "~~~~~~@~~~~~~://SITO/js/scripts.js:304:299",
    "columnNumber": 299,
    "fileName": "http://SITO/js/scripts.js",
    "functionName": "pre",
    "lineNumber": 304
  },
  {
    "source": "Qa/<@http://SITO/js/scripts.js:28:132",
    "columnNumber": 132,
    "fileName": "http://SITO/js/scripts.js",
    "functionName": "Qa/<",
    "lineNumber": 28
  },
  {
    "source": "~~~~~~@~~~~~~://SITO/js/scripts.js:96:274",
    "columnNumber": 274,
    "fileName": "http://SITO/js/scripts.js",
    "functionName": "ra",
    "lineNumber": 96
  },
  {
    "source": "~~~~~~@~~~~~~://SITO/js/scripts.js:81:151",
    "columnNumber": 151,
    "fileName": "http://SITO/js/scripts.js",
    "functionName": "p",
    "lineNumber": 81
  },
  {
    "source": "~~~~~~@~~~~~~://SITO/js/scripts.js:73:411",
    "columnNumber": 411,
    "fileName": "http://SITO/js/scripts.js",
    "functionName": "g",
    "lineNumber": 73
  },
  {
    "source": "~~~~~~@~~~~~~://SITO/js/scripts.js:81:282",
    "columnNumber": 282,
    "fileName": "http://SITO/js/scripts.js",
    "functionName": "p",
    "lineNumber": 81

This later trigger another error:
Platform: UniPD Leaks
Host: whistleblowing.unipd.it (2qeqgswgbzhmk76v.onion)
Version: 3.1.9

URL: /submission

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

Error Message: TypeError: Cannot read property 'value' of undefined

Stacktrace:
[
  {
    "source": "    at b.$scope.onAnswerUpdate (https://whistleblowing.unipd.it/js/scripts.js:20328:70)", 
    "columnNumber": 70, 
    "fileName": "https://whistleblowing.unipd.it/js/scripts.js", 
    "functionName": "b.$scope.onAnswerUpdate", 
    "lineNumber": 20328
  }, 
  {
    "source": "    at fn (https://whistleblowing.unipd.it/js/scripts.js:255:261", 
    "columnNumber": 261, 
    "fileName": "https://whistleblowing.unipd.it/js/scripts.js", 
    "functionName": "fn", 
    "lineNumber": 255
  }, 
  {
    "source": "    at b.$eval (https://whistleblowing.unipd.it/js/scripts.js:162:514)", 
    "columnNumber": 514, 
    "fileName": "https://whistleblowing.unipd.it/js/scripts.js", 
    "functionName": "b.$eval", 
    "lineNumber": 162
  }, 
  {
    "source": "    at Object.pre (https://whistleblowing.unipd.it/js/scripts.js:304:301)", 
    "columnNumber": 301, 
    "fileName": "https://whistleblowing.unipd.it/js/scripts.js", 
    "functionName": "Object.pre", 
    "lineNumber": 304
  }, 
  {
    "columnNumber": 134, 
    "fileName": "https://whistleblowing.unipd.it/js/scripts.js", 
    "source": "    at https://whistleblowing.unipd.it/js/scripts.js:28:134", 
    "lineNumber": 28
  }, 
  {
    "source": "    at ra (https://whistleblowing.unipd.it/js/scripts.js:96:274)", 
    "columnNumber": 274, 
    "fileName": "https://whistleblowing.unipd.it/js/scripts.js", 
    "functionName": "ra", 
    "lineNumber": 96
  }, 
  {
    "source": "    at p (https://whistleblowing.unipd.it/js/scripts.js:81:151)", 
    "columnNumber": 151, 
    "fileName": "https://whistleblowing.unipd.it/js/scripts.js", 
    "functionName": "p", 
    "lineNumber": 81
  }, 
  {
    "source": "    at g (https://whistleblowing.unipd.it/js/scripts.js:73:411)", 
    "columnNumber": 411, 
    "fileName": "https://whistleblowing.unipd.it/js/scripts.js", 
    "functionName": "g", 
    "lineNumber": 73
  }, 
  {
    "source": "    at p (https://whistleblowing.unipd.it/js/scripts.js:81:282)", 
    "columnNumber": 282, 
    "fileName": "https://whistleblowing.unipd.it/js/scripts.js", 
    "functionName": "p", 
    "lineNumber": 81
  }, 
  {
    "source": "    at g (https://whistleblowing.unipd.it/js/scripts.js:73:411)", 
    "columnNumber": 411, 
    "fileName": "https://whistleblowing.unipd.it/js/scripts.js", 
    "functionName": "g", 
    "lineNumber": 73
  }
]

**Comment by evilaliv3** [comment]
Actually i've alredy retested the issue on many configurations and versions and the issue appears to not be reproducible.

Let's way for new user feedback or access to the development setup.

**Comment by fpietrosanti** [comment]
Questionnaire triggering the error attached
[Questionario UnipdLeaks.json.zip](https://github.com/globaleaks/GlobaLeaks/files/2141509/Questionario.UnipdLeaks.json.zip)

**Comment by evilaliv3** [comment]
Closing as outdated.
