### ISSUE TITLE
Unhandled sqlite3.IntegrityError: FOREIGN KEY constraint failed in GL 3.2.3

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#2376]
Platform: xxxx
Host: xxxx
Version: 3.2.3

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 721, in _commit_impl
    self.engine.dialect.do_commit(self.connection)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 443, in do_commit
    dbapi_connection.commit()

sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 112, in _wrap
    session.commit()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 465, in commit
    t[1].commit()

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1632, in commit
    self._do_commit()

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1663, in _do_commit
    self.connection._commit_impl()

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 723, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 721, in _commit_impl
    self.engine.dialect.do_commit(self.connection)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 443, in do_commit
    dbapi_connection.commit()

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed

**Comment by evilaliv3** [comment]
Closing as outdated
