### ISSUE TITLE
Unhandled exception AttributeError: ESMTPSenderFactory instance has no attribute 'result'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#2387]
Platform: Comune di xxxx
Host: globaleaks.comune.xxxxx
Version: 3.2.3

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()

  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)

  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 430, in dataReceived
    self._flushReceiveBIO()

  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 395, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)

  File "/usr/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/endpoints.py", line 116, in dataReceived
    return self._wrappedProtocol.dataReceived(data)

  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)

  File "/usr/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 915, in lineReceived
    why = self._failresponse(self.code,'\n'.join(self.resp))

  File "/usr/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 1243, in esmtpAUTHDeclined
    self.sendError(AUTHDeclinedError(code, resp, self.log.str()))

  File "/usr/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 1721, in sendError
    self.factory.result.errback(exc)

AttributeError: ESMTPSenderFactory instance has no attribute 'result'

**Comment by fpietrosanti** [comment]
happened again on latest 3.4.1 on MexicoLeaks

**Comment by evilaliv3** [comment]
Closing as stale and outdated.
