### ISSUE TITLE
Unhandled exception on Cannot read property 'enable_rc_to_wb_files' of undefined

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#2451]
Platform: 
Host:  ()
Version: 3.4.1

URL: /status/800fb712-f66c-4282-9d84-5e8c318a5361

User Agent:  Chrome/70.0.3538.77 

Error Message: TypeError: Cannot read property 'enable_rc_to_wb_files' of undefined

Stacktrace:
[
  {
    "columnNumber": 56,
    "lineNumber": 19427,
    "fileName": "http://192.168.30.xx/js/scripts.js",
    "functionName": "m.$scope.showWBFileUpload",
    "source": "    at m.$scope.showWBFileUpload (http://192.168.30.xx/js/scripts.js:19427:56)"
  },
  {
    "columnNumber": 35,
    "lineNumber": 254,
    "fileName": "http://192.168.30.xx/js/scripts.js",
    "functionName": "fn",
    "source": "    at fn (http://192.168.30.xx/js/scripts.js:254:35"
  },

**Comment by evilaliv3** [comment]
Closing as stale and outdated.
