### ISSUE TITLE
GL 3.5.7: Unhandled exception in notif.update in update_notification: ValueError: Cannot assign <globaleaks.models.Config object at 0xffffab274b50> with <type 'float'>

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#2473]
Platform: try.globaleaks.org
Host: try.globaleaks.org (bvidswzoj322engc.onion)
Version: 3.5.7

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 109, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/notification.py", line 46, in update_notification
    notif.update(request)

  File "/usr/lib/python2.7/dist-packages/globaleaks/models/config.py", line 35, in update
    configs[k].set_v(request[k])

  File "/usr/lib/python2.7/dist-packages/globaleaks/models/__init__.py", line 337, in set_v
    raise ValueError("Cannot assign %s with %s" % (self, type(val)))

ValueError: Cannot assign <globaleaks.models.Config object at 0xffffab274b50> with <type 'float'>

**Comment by evilaliv3** [comment]
Surely a bug that we could address easily with a cast as for https://github.com/globaleaks/GlobaLeaks/issues/2474

I guess both the two errors have been triggered by a user performing a penetration test.

**Comment by evilaliv3** [comment]
Closing as stale and outdated.
