### ISSUE TITLE
Unhandled Exception error on SNI /backend/globaleaks/utils/sni.py#L161

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/globaleaks-whistleblowing-software#2705]
**Current behavior**
There are multiple errors in globaleaks.log as checked on ALAC of TI-it

2019-09-19 06:56:23+0000 [-] on_finish
2019-09-19 06:57:37+0000 [-] From cffi callback <function selectContext at 0x7f2da5279668>:
2019-09-19 06:57:37+0000 [-] Traceback (most recent call last):
2019-09-19 06:57:37+0000 [-]   File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1003, in wrapper
2019-09-19 06:57:37+0000 [-]     callback(Connection._reverse_mapping[ssl])
2019-09-19 06:57:37+0000 [-]   File "/usr/lib/python2.7/dist-packages/globaleaks/utils/sni.py", line 149, in selectContext
2019-09-19 06:57:37+0000 [-]     common_name = connection.get_servername().decode('utf-8')
2019-09-19 06:57:37+0000 [-] AttributeError: 'NoneType' object has no attribute 'decode'

This can be tracked down to the line:
https://github.com/globaleaks/GlobaLeaks/blob/d353dea090163523ea94076690e530e1dc9d81b9/backend/globaleaks/utils/sni.py#L161

**Expected behavior**
The error should not be present

**Comment by evilaliv3** [comment]
This error in my opinon could be old with relation to latest SNI revision.

**Comment by evilaliv3** [comment]
Closing as outdated
