### ISSUE TITLE
Questionnaire visualization failure when occasionally a recipient user is disabled

### ISSUE THREAD

**Issue by elbill** [globaleaks/globaleaks-whistleblowing-software#3023]
**Describe the bug**
For one context the questionnaire does not appear, only the step's tabs. For a test context with exactly the same questionnaire, it works fine.
**To Reproduce**
Can not reproduce. have a look at:

epathla.fraudline.gr

the hidden test context that works fine:
https://epathla.fraudline.gr/#/submission?context=b4e98a5a-57c9-47ef-8b67-ceb9be408df1

**Expected behavior**

**Screenshots**

![test](https://user-images.githubusercontent.com/23246886/124255273-a5b6cb00-db32-11eb-8bc7-f2e9a543b535.png)

**Smartphone (please complete the following information):**
 - Device: smartphone
 - OS: android 11
 - Browser mobile chrome, opera

**Additional context**
error log

Host: epathla.fraudline.gr (kvmodo4ernfh6dgzbztak4xng2353g6bmvki5omomiffuzkfrqu6bfad.onion)
Version: 4.2.10

URL: /

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

Error Message: TypeError: Cannot read property 'forcefully_selected' of undefined

Stacktrace:
[
  {
    "columnNumber": 244225,
    "lineNumber": 64,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "source": "    at https://epathla.fraudline.gr/js/scripts.min.js:64:244225"
  },
  {
    "columnNumber": 1541,
    "lineNumber": 8,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "Object.x [as forEach]",
    "source": "    at Object.x [as forEach] (https://epathla.fraudline.gr/js/scripts.min.js:8:1541)"
  },
  {
    "columnNumber": 244135,
    "lineNumber": 64,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "Object.t.setContextReceivers",
    "source": "    at Object.t.setContextReceivers (https://epathla.fraudline.gr/js/scripts.min.js:64:244135)"
  },
  {
    "columnNumber": 262452,
    "lineNumber": 64,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "Object.onAnswersUpdate",
    "source": "    at Object.onAnswersUpdate (https://epathla.fraudline.gr/js/scripts.min.js:64:262452)"
  },
  {
    "columnNumber": 666645,
    "lineNumber": 64,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "source": "    at https://epathla.fraudline.gr/js/scripts.min.js:64:666645"
  },
  {
    "columnNumber": 101420,
    "lineNumber": 8,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "d.$digest",
    "source": "    at d.$digest (https://epathla.fraudline.gr/js/scripts.min.js:8:101420)"
  },
  {
    "columnNumber": 103100,
    "lineNumber": 8,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "t.$apply",
    "source": "    at t.$apply (https://epathla.fraudline.gr/js/scripts.min.js:8:103100)"
  },
  {
    "columnNumber": 151930,
    "lineNumber": 8,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "HTMLButtonElement.<anonymous>",
    "source": "    at HTMLButtonElement.<anonymous> (https://epathla.fraudline.gr/js/scripts.min.js:8:151930)"
  },
  {
    "columnNumber": 17501,
    "lineNumber": 8,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "Rt",
    "source": "    at Rt (https://epathla.fraudline.gr/js/scripts.min.js:8:17501)"
  },
  {
    "columnNumber": 20371,

    "lineNumber": 8,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "HTMLButtonElement.n",
    "source": "    at HTMLButtonElement.n (https://epathla.fraudline.gr/js/scripts.min.js:8:20371)"
  }
]

**Comment by evilaliv3** [comment]
Thank you for reporting this @elbill 

We tried to reproduce this issue on Firefox and Chome both on desktop and on mobile but unfortunately we are not able to reproduce it.

The issue seems to be IOS specific? Do you confirm this from your point of view?

**Comment by elbill** [comment]
have you tried to access epathla.fraudline.gr and worked?
I tried with opera, chrome on win 10 and chrome on android with the same results

does not work on
https://epathla.fraudline.gr/#/submission?context=d386ac53-ec33-4d03-8a07-814c0db49b68

Works on almost identical (just different recipients)
https://epathla.fraudline.gr/#/submission?context=b4e98a5a-57c9-47ef-8b67-ceb9be408df1

**Comment by elbill** [comment]
The OS info on the original issue report was the example. Forgot to fill it in. Sorry

**Comment by elbill** [comment]
Found what causes this. I disabled one user that was set as a recipient, and this caused the error. Not sure if this a bug. Sometimes you may have to disable one user without removing them from context .

**Comment by evilaliv3** [comment]
Thank you @elbill, this is actually a bug that should be fixed and it is probably related to some caches not correctly resetted and in general the code of the client that could probably be more resilit to these situations.

**Comment by offrau** [comment]
When this bug will be fixed?.  Thanks

**Comment by evilaliv3** [comment]
Closing as stale and probably resolved.
