### ISSUE TITLE
Getting error email multiple times : Error Message: TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by divium-singh** [globaleaks/globaleaks-whistleblowing-software#3038]
Hello,

I am getting 4 emails at a time stating " Error Message: TypeError: Cannot read property 'split' of undefined ".
I've started getting this after the update from v4.2.12 to v4.2.13.

Note: I've done an apt-update and apt-upgrade on ubuntu. And i am using version 20 LTS. 

Any idea why this error message?

Version: 4.2.13

URL: /status/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

Error Message: TypeError: Cannot read property 'split' of undefined

Stacktrace:
[
  {
    "columnNumber": 240267,
    "lineNumber": 64,
    "fileName": "http://complaints.icac.mu/js/scripts.min.js",
    "source": "    at http://complaints.icac.mu/js/scripts.min.js:64:240267"
  },
  {
    "columnNumber": 114346,
    "lineNumber": 8,
    "fileName": "http://complaints.icac.mu/js/scripts.min.js",
    "functionName": "Array.<anonymous>",
    "source": "    at Array.<anonymous> (http://complaints.icac.mu/js/scripts.min.js:8:114346)"
  },
  {
    "columnNumber": 114327,
    "lineNumber": 8,
    "fileName": "http://complaints.icac.mu/js/scripts.min.js",
    "source": "    at http://complaints.icac.mu/js/scripts.min.js:8:114327"
  },
  {
    "columnNumber": 93072,
    "lineNumber": 8,
    "fileName": "http://complaints.icac.mu/js/scripts.min.js",
    "source": "    at http://complaints.icac.mu/js/scripts.min.js:8:93072"
  },
  {
    "columnNumber": 101303,
    "lineNumber": 8,
    "fileName": "http://complaints.icac.mu/js/scripts.min.js",
    "functionName": "d.$digest",
    "source": "    at d.$digest (http://complaints.icac.mu/js/scripts.min.js:8:101303)"
  },
  {
    "columnNumber": 103100,
    "lineNumber": 8,
    "fileName": "http://complaints.icac.mu/js/scripts.min.js",
    "functionName": "d.$apply",
    "source": "    at d.$apply (http://complaints.icac.mu/js/scripts.min.js:8:103100)"
  },
  {
    "columnNumber": 66702,
    "lineNumber": 8,
    "fileName": "http://complaints.icac.mu/js/scripts.min.js",
    "functionName": "_",
    "source": "    at _ (http://complaints.icac.mu/js/scripts.min.js:8:66702)"
  },
  {
    "columnNumber": 68927,
    "lineNumber": 8,
    "fileName": "http://complaints.icac.mu/js/scripts.min.js",
    "functionName": "C",
    "source": "    at C (http://complaints.icac.mu/js/scripts.min.js:8:68927)"
  },
  {
    "columnNumber": 68274,
    "lineNumber": 8,
    "fileName": "http://complaints.icac.mu/js/scripts.min.js",
    "functionName": "XMLHttpRequest.b.onload",
    "source": "    at XMLHttpRequest.b.onload (http://complaints.icac.mu/js/scripts.min.js:8:68274)"
  }
]

**Comment by divium-singh** [comment]
Today, i'm getting another type of error. I've got the email below twice at the same time.

Platform: ICAC
Host: 192.168.1.138 (ooud3ncxqdyno2ghkrpbsqeh55p35lcur32fj26y5m3az4yuoj4zhsqd.onion)
Version: 4.2.13

URL: /status/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0

Error Message: TypeError: e is undefined

Stacktrace:
[
  {
    "columnNumber": 240258,
    "lineNumber": 64,
    "fileName": "http://192.168.1.138/js/scripts.min.js",
    "source": "@http://192.168.1.138/js/scripts.min.js:64:240258"
  },
  {
    "columnNumber": 114346,
    "lineNumber": 8,
    "fileName": "http://192.168.1.138/js/scripts.min.js",
    "functionName": "recurse/<",
    "source": "recurse/<@http://192.168.1.138/js/scripts.min.js:8:114346"
  },
  {
    "columnNumber": 114327,
    "lineNumber": 8,
    "fileName": "http://192.168.1.138/js/scripts.min.js",
    "functionName": "recurse/<",
    "source": "recurse/<@http://192.168.1.138/js/scripts.min.js:8:114327"
  },
  {
    "columnNumber": 93073,
    "lineNumber": 8,
    "fileName": "http://192.168.1.138/js/scripts.min.js",
    "functionName": "l/<",
    "source": "l/<@http://192.168.1.138/js/scripts.min.js:8:93073"
  },
  {
    "columnNumber": 101303,
    "lineNumber": 8,
    "fileName": "http://192.168.1.138/js/scripts.min.js",
    "functionName": "$digest",
    "source": "$~~~~~~@~~~~~~://192.168.1.138/js/scripts.min.js:8:101303"
  },
  {
    "columnNumber": 103100,
    "lineNumber": 8,
    "fileName": "http://192.168.1.138/js/scripts.min.js",
    "functionName": "$apply",
    "source": "$~~~~~~@~~~~~~://192.168.1.138/js/scripts.min.js:8:103100"
  },
  {
    "columnNumber": 66702,
    "lineNumber": 8,
    "fileName": "http://192.168.1.138/js/scripts.min.js",
    "functionName": "_",
    "source": "~~~~~~@~~~~~~://192.168.1.138/js/scripts.min.js:8:66702"
  },
  {
    "columnNumber": 68927,
    "lineNumber": 8,
    "fileName": "http://192.168.1.138/js/scripts.min.js",
    "functionName": "C",
    "source": "~~~~~~@~~~~~~://192.168.1.138/js/scripts.min.js:8:68927"
  },
  {
    "columnNumber": 68274,
    "lineNumber": 8,
    "fileName": "http://192.168.1.138/js/scripts.min.js",
    "functionName": "Kn/this.$get</</</b.onload",
    "source": "Kn/this.$get</</</~~~~~~@~~~~~~://192.168.1.138/js/scripts.min.js:8:68274"
  }
]

**Comment by evilaliv3** [comment]
Thank you for reporting these errors @divium-singh, we will anyhow proceed debugging them and see if they could be fixed or are just related to interrupted connections.

Actually in fact globaleaks in any error condition does always generates email like those ut you can safely ignore them as they typically are not critical.

Please if you can always use separated tickets to report separated issues that could help us tracking them more easily.

**Comment by COLONAYUSH** [comment]
Hey @evilaliv3 
I would like to work on that as my first issue

**Comment by divium-singh** [comment]
@evilaliv3,

Thank you for the fast response. Alright, next time i will create different tickets for different errors.
@evilaliv3  and @COLONAYUSH , let me know if you need anything to debug. i can send you a backup copy if needed.

Regards,
Divium

**Comment by evilaliv3** [comment]
Thank you @COLONAYUSH, it would be actually great if you would try to debug which could be the reason of these two failures that could be related to a precondition that is not verified or a specific faulire on a specific browser.

**Comment by evilaliv3** [comment]
Closing as stale and probably resolved.
