### ISSUE TITLE
Exception on UNIQUE constraint failed: internaltip.tid, internaltip.progressive

### ISSUE THREAD

**Issue by aetdr** [globaleaks/globaleaks-whistleblowing-software#3390]
### What version of GlobaLeaks are you using?

Hi @evilaliv3 

I am seeing this error with v4.10.18

```
Platform: 
Host: 
Version: 4.10.18

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)

sqlite3.IntegrityError: UNIQUE constraint failed: internaltip.tid, internaltip.progressive


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 178, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/submission.py", line 249, in create_submission
    return db_create_submission(session, tid, request, user_session, client_using_tor, client_using_mobile)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/submission.py", line 186, in db_create_submission
    session.flush()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2577, in _flush
    flush_context.execute()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    result = cached_connections[connection].execute(

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: internaltip.tid, internaltip.progressive
[SQL: INSERT INTO internaltip (id, tid, creation_date, update_date, context_id, progressive, tor, mobile, score, expiration_date, enable_two_way_comments, enable_two_way_messages, enable_attachments, enable_whistleblower_identity, important, label, last_access, status, substatus, receipt_hash, crypto_prv_key, crypto_pub_key, crypto_tip_pub_key, crypto_tip_prv_key, crypto_files_pub_key) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: removed]
(Background on this error at: http://sqlalche.me/e/gkpj)

```

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

email notifications sent to admins with the content above

**Comment by ncidgomez** [comment]
I have the same problem with same versions when I try to upgrade.
