### ISSUE TITLE
UnicodeDecodeError Unicode decoding error.

### ISSUE THREAD

**Issue by aetdr** [globaleaks/globaleaks-whistleblowing-software#3408]
### What version of GlobaLeaks are you using?

4.10.18

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Hi @evilaliv3 

I have seen multiple mails with this error.

```
Platform: 
Host: 
Version: 4.10.18

UnicodeDecodeError Unicode decoding error.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run
    yield self.operation()

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/tor_exit_set.py", line 16, in processData
    for ip in re.findall(r'ExitAddress ([^ ]*) ', data.decode()):

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

```

**Comment by evilaliv3** [comment]
Thank you @aetdr for reporting this.

We will check this and make a patch as soon that we manage to reproduce it.

**Comment by andihuber** [comment]
I am also getting this emails on the test installation:

Version:  4.11.5

UnicodeDecodeError Unicode decoding error.

Traceback (most recent call last):

 File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 235, in process
   self.render(resrc)

 File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 302, in render
   body = resrc.render(self)

 File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 392, in render
   request_path = request.path.decode()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 0: invalid continuation byte

**Comment by evilaliv3** [comment]
thank you @andihuber for reporting this.

actually the error you are reporting is happening on a different component from what reported but maybe we could manage to fix this more easily from the one already reported

**Comment by evilaliv3** [comment]
Closing as outdated
